"""
pdf_export.py
─────────────
Generates downloadable PDF reports (OCR lab summaries and risk-assessment
results) using fpdf2. Requires: pip install fpdf2

Kept dependency-isolated from the rest of the app — if fpdf2 isn't
installed, PDF_AVAILABLE is False and callers should hide the download
button rather than crash.
"""

from datetime import datetime

try:
    from fpdf import FPDF
    PDF_AVAILABLE = True
except ImportError as _e:
    PDF_AVAILABLE = False
    print("PDF_EXPORT IMPORT ERROR:", _e)


NAVY   = (11, 18, 32)
CYAN   = (0, 180, 220)
RED    = (200, 40, 60)
AMBER  = (200, 130, 20)
GREEN  = (30, 140, 90)
GREY   = (90, 100, 115)
BLACK  = (20, 24, 32)


def _safe(text) -> str:
    """Replace Unicode punctuation that the core Helvetica font can't render
    (fpdf2 raises instead of silently dropping these) with ASCII equivalents."""
    if text is None:
        return ""
    text = str(text)
    replacements = {
        "\u2014": "-",   # em dash —
        "\u2013": "-",   # en dash –
        "\u2022": "-",   # bullet •
        "\u2018": "'",   # left single quote ‘
        "\u2019": "'",   # right single quote ’
        "\u201c": '"',   # left double quote “
        "\u201d": '"',   # right double quote ”
        "\u2026": "...", # ellipsis …
        "\u00a0": " ",   # non-breaking space
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)
    # Final safety net: drop anything else outside latin-1 rather than crash.
    return text.encode("latin-1", "ignore").decode("latin-1")


def _header(pdf, title, subtitle=""):
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, 210, 28, style="F")
    pdf.set_xy(12, 8)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 8, "MedCore AI", ln=1)
    pdf.set_x(12)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(150, 220, 240)
    pdf.cell(0, 6, _safe(title), ln=1)
    if subtitle:
        pdf.set_x(12)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(200, 210, 220)
        pdf.cell(0, 5, _safe(subtitle), ln=1)
    pdf.set_y(34)
    pdf.set_text_color(*BLACK)


def _section_heading(pdf, text):
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 8, _safe(text), ln=1)
    pdf.set_draw_color(210, 215, 225)
    pdf.line(12, pdf.get_y(), 198, pdf.get_y())
    pdf.ln(2)
    pdf.set_text_color(*BLACK)


def _body_line(pdf, text, size=10, color=BLACK, bold=False):
    pdf.set_font("Helvetica", "B" if bold else "", size)
    pdf.set_text_color(*color)
    pdf.set_x(pdf.l_margin)
    try:
        pdf.multi_cell(pdf.epw, 6, _safe(text), new_x="LMARGIN", new_y="NEXT")
    except TypeError:
        pdf.multi_cell(0, 6, _safe(text))
        pdf.set_x(pdf.l_margin)


def _footer_note(pdf):
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GREY)
    pdf.set_x(pdf.l_margin)
    try:
        pdf.multi_cell(
            pdf.epw, 5,
            "This report is generated by an AI-assisted clinical decision-support tool for "
            "research and educational purposes. It is not a medical diagnosis. Please consult "
            "a qualified doctor before making any medical decisions.",
            new_x="LMARGIN", new_y="NEXT"
        )
    except TypeError:
        pdf.multi_cell(
            0, 5,
            "This report is generated by an AI-assisted clinical decision-support tool for "
            "research and educational purposes. It is not a medical diagnosis. Please consult "
            "a qualified doctor before making any medical decisions."
        )
        pdf.set_x(pdf.l_margin)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_x(pdf.l_margin)
    pdf.cell(0, 5, f"Generated on {datetime.now().strftime('%d %b %Y, %H:%M')}", ln=1)


def _get_bytes(pdf) -> bytes:
    raw = pdf.output()
    return bytes(raw) if not isinstance(raw, str) else raw.encode("latin-1")


def build_ocr_summary_pdf(patient_info: dict, all_values: dict, abnormal_flags: list, summary_text: str) -> bytes:
    """PDF version of an OCR lab-report summary (as shown in the OCR Reports tab)."""
    if not PDF_AVAILABLE:
        raise RuntimeError("fpdf2 is not installed — pip install fpdf2")

    pdf = FPDF()
    pdf.add_page()
    _header(pdf, "Lab Report Summary", "OCR + NLP Extracted Biomarkers")

    if patient_info:
        bits = [f"{k.replace('_',' ').title()}: {v}" for k, v in patient_info.items() if v]
        if bits:
            _body_line(pdf, "  ·  ".join(bits), size=10, color=GREY)
            pdf.ln(2)

    _section_heading(pdf, "Overall Assessment")
    if abnormal_flags:
        crit = [f for f in abnormal_flags if "critical" in f["flag"].lower()]
        if crit:
            _body_line(pdf, f"{len(crit)} value(s) critically abnormal, {len(abnormal_flags)-len(crit)} other(s) worth watching.", color=RED, bold=True)
        else:
            _body_line(pdf, f"{len(abnormal_flags)} value(s) outside the normal range.", color=AMBER, bold=True)
    else:
        _body_line(pdf, "All extracted values are within normal range.", color=GREEN, bold=True)

    _section_heading(pdf, "Extracted Values")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(235, 238, 245)
    pdf.cell(70, 7, "Parameter", border=1, fill=True)
    pdf.cell(40, 7, "Value", border=1, fill=True)
    pdf.cell(40, 7, "Normal Range", border=1, fill=True)
    pdf.cell(36, 7, "Status", border=1, fill=True, ln=1)

    abnormal_by_key = {f["key"]: f for f in abnormal_flags}
    pdf.set_font("Helvetica", "", 9)
    for key, val in all_values.items():
        label = key.replace("_", " ").title()
        if key in abnormal_by_key:
            f = abnormal_by_key[key]
            unit, normal, flag = f["unit"], f["normal"], f["flag"]
            color = RED if ("critical" in flag.lower() or "high" in flag.lower()) else AMBER
        else:
            unit, normal, flag = "", "-", "Normal"
            color = GREEN
        pdf.set_text_color(*BLACK)
        pdf.cell(70, 6.5, _safe(label)[:34], border=1)
        pdf.cell(40, 6.5, _safe(f"{val} {unit}")[:18], border=1)
        pdf.cell(40, 6.5, _safe(normal)[:18], border=1)
        pdf.set_text_color(*color)
        pdf.cell(36, 6.5, _safe(flag)[:16], border=1, ln=1)

    pdf.set_text_color(*BLACK)
    _section_heading(pdf, "Summary")
    _body_line(pdf, summary_text or "No summary available.")

    _footer_note(pdf)
    return _get_bytes(pdf)


def build_diagnosis_pdf(
    condition: str, level: str, risk_pct: float, confidence: float,
    prediction_label: str, key_inputs: dict, recommendations: dict,
) -> bytes:
    """PDF version of a heart/cancer risk-assessment result."""
    if not PDF_AVAILABLE:
        raise RuntimeError("fpdf2 is not installed — pip install fpdf2")

    level_color = RED if "HIGH" in level.upper() else AMBER if "MODERATE" in level.upper() else GREEN

    pdf = FPDF()
    pdf.add_page()
    _header(pdf, f"{condition} Risk Assessment", "AI-Assisted Clinical Decision Support")

    _section_heading(pdf, "Result")
    _body_line(pdf, f"Risk Level: {level}", size=13, color=level_color, bold=True)
    _body_line(pdf, f"Risk Score: {risk_pct}%   ·   Model Confidence: {confidence}%   ·   Prediction: {prediction_label}")

    if key_inputs:
        _section_heading(pdf, "Key Input Values")
        pdf.set_font("Helvetica", "", 9)
        for k, v in key_inputs.items():
            _body_line(pdf, f"- {k}: {v}", size=9.5)

    if recommendations:
        for section, items in recommendations.items():
            if not items:
                continue
            _section_heading(pdf, section)
            pdf.set_font("Helvetica", "", 9.5)
            for item in items:
                text = item if isinstance(item, str) else "  -  ".join(str(x) for x in item)
                _body_line(pdf, f"- {text}", size=9.5)

    _footer_note(pdf)
    return _get_bytes(pdf)